replicaCount: 4

image:
  repository: cloudketan/python
  tag: "p1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007

containerPort: 5000

resources: {}

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false

podLabels: {}
podAnnotations: {}

# Fix ServiceAccount template
serviceAccount:
  create: true
  name: ""

# Fix httproute template
httpRoute:
  enabled: false
